pipeline {
    agent any

    parameters {
        string(name: 'KEY_BACKUP_ENV', defaultValue: 'hey.zip', description: '')
        string(name: 'MONGO_HOST', defaultValue: 'develop.uf9uoog.mongodb.net', description: '')
        string(name: 'MONGO_USER', defaultValue: 'heyDev', description: '')
        string(name: 'MONGO_PASSWORD', defaultValue: '', description: '')
        string(name: 'MONGO_DB', defaultValue: 'hey-dev', description: '')
    }

    stages {
        stage('Download backup') {
            steps {
                withAWS(credentials: 'awscredentials') {
                    s3Download(file: KEY_BACKUP_ENV, bucket: 'backups', path:'~/backups')
                }
            }
        }

        stage('restore') {
            steps {
                script {
                    sh 'mongorestore --uri="mongodb-srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority" --db=${MONGO_DB} ~/backups/${KEY_BACKUP_ENV} --gzip --drop'
                }
            }
        }

        stage('Delete backup') {
            steps {
                script {
                    sh 'rm -r ~/backups'
                }
            }
        }
    }
}
