pipeline {
    agent any

    parameters {
        string(name: 'KEY_BACKUP_ENV', defaultValue: 'hey.zip', description: '')
        choice(name: 'MONGO_DB', choices: ['hey-dev', 'hey-qa'], description: 'Selecciona la base de datos', )
        string(name: 'MONGO_HOST', defaultValue: 'develop.uf9uoog.mongodb.net', description: '')
    }

    environment {
        FOLDER_UNZIP_BACKUP = new Date().format("yyyyMMddHHmmss")
    }

    stages {
        stage('Prepare env') {
            steps {
                script {
                    try {
                        sh 'apt-get install gnupg curl -y'
                        sh 'curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor'
                        sh 'echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list'
                        sh 'apt-get update -y && apt-get install -y mongodb-org-tools'
                        sh 'mongorestore --version'
                    } catch (Exception e) {
                        echo "Skip mongo-tools installation"
                    }
                }
            }
        }

        stage('Download backup') {
            steps {
                script {
                    withAWS(credentials: 'awscredentials', region: 'us-east-2') {
                        s3Download(file: "/tmp/${KEY_BACKUP_ENV}", bucket: 'sellia-backups', path: "${KEY_BACKUP_ENV}", force: true)
                    }
                }
            }
        }

        stage('restore') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'mongodbuser', passwordVariable: 'MONGO_PASSWORD', usernameVariable: 'MONGO_USER')]) {
                    script {
                        sh 'unzip /tmp/${KEY_BACKUP_ENV} -d /tmp/${FOLDER_UNZIP_BACKUP}'
                        sh 'mongorestore --uri="mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority" --nsInclude="${MONGO_DB}.*" /tmp/${FOLDER_UNZIP_BACKUP}  --gzip --drop'
                    }
                }
            }
        }

        stage('Delete backup') {
            steps {
                script {
                    sh 'rm -r /tmp/${KEY_BACKUP_ENV} /tmp/${FOLDER_UNZIP_BACKUP}'
                }
            }
        }
    }
}
